name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    
    env:
      P4_ROOT: ./p4root
      P4_NAME: p4
      P4_URL: https://ftp.perforce.com/perforce/r25.1/bin.linux26x86_64/p4
      P4D_NAME: p4d
      P4D_URL: https://ftp.perforce.com/perforce/r25.1/bin.linux26x86_64/p4d
      P4SSLDIR: ${{ github.workspace }}/p4ssl

      P4_PORT: ssl:localhost:1666
      P4_USER: admin
      P4_PASS: password

    steps:
    - uses: actions/checkout@v4

    - name: Make p4 directories
      run: |
        if [ ! -d $P4_ROOT ]; then
          mkdir -p $P4_ROOT
        fi
        if [ ! -d $P4SSLDIR ]; then
          mkdir -p $P4SSLDIR
          chmod 700 $P4SSLDIR
        fi

    - name: Cache p4
      uses: actions/cache@v3
      with:
        path: ${{ env.P4_ROOT}}/${{ env.P4_NAME }}
        key: ${{ env.P4_URL}}
    - name: Download p4
      run: |
        if [ ! -f $P4_ROOT/$P4_NAME ]; then
          wget -O $P4_ROOT/$P4_NAME $P4_URL
        fi
        chmod +x $P4_ROOT/$P4_NAME

    - name: Cache p4d
      uses: actions/cache@v3
      with:
        path: ${{ env.P4_ROOT}}/${{ env.P4D_NAME }}
        key: ${{ env.P4D_URL}}
    - name: Download p4d
      run: |
        if [ ! -f $P4_ROOT/$P4D_NAME ]; then
          wget -O $P4_ROOT/$P4D_NAME $P4D_URL
        fi
        chmod +x $P4_ROOT/$P4D_NAME

    - name: Generate SSL certs
      run: |
        $P4_ROOT/$P4D_NAME -Gc
        $P4_ROOT/$P4D_NAME -Gf

    - name: Launch p4d
      run: |
        $P4_ROOT/$P4D_NAME -xi -r $P4_ROOT
        $P4_ROOT/$P4D_NAME -r $P4_ROOT -p $P4_PORT -d
        sleep 2
        
    - name: Create Perforce admin user
      run: |
        $P4_ROOT/$P4_NAME -p $P4_PORT trust -f -y
        $P4_ROOT/$P4_NAME -p $P4_PORT user -f $P4_USER <<EOF
        User: $P4_USER
        Email: ${P4_USER}@example.com
        FullName: Perforce Admin
        EOF

        $P4_ROOT/$P4_NAME -p $P4_PORT -u $P4_USER passwd -O "" -P $P4_PASS

        $P4_ROOT/$P4_NAME -p $P4_PORT protect -i <<EOF
        Protections:
            super user admin * //...
        EOF
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
