name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    
    env:
      P4_ROOT: ./p4root
      P4D_NAME: p4d
      P4D_URL: https://ftp.perforce.com/perforce/r25.1/bin.linux26x86_64/p4d

    steps:
    - uses: actions/checkout@v4

    - name: Make p4root
      run: |
        if [ ! -d $P4_ROOT ]; then
          mkdir -p $P4_ROOT
        fi

    - name: Cache p4d
      uses: actions/cache@v3
      with:
        path: ${{ env.P4_ROOT}}/${{ env.P4D_NAME }}
        key: ${{ env.P4D_URL}}
        
    - name: Download p4d
      run: |
        if [ ! -f $P4_ROOT/$P4D_NAME ]; then
          wget -O $P4_ROOT/$P4D_NAME $P4D_URL
        fi
        chmod +x $P4_ROOT/$P4D_NAME
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
